name: codiny_platform_app
description: "Driving exam preparation platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  shared_preferences: ^2.5.4
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  table_calendar: ^3.1.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/exam_images/
    - assets/courses/
    - assets/traffic_signs/
